### ISSUE TITLE
[Bug] Example doesn't compile

### ISSUE THREAD

**Issue by yevgenypats** [temporalio/temporal-ecommerce#11]
**Describe the bug**

`go run worker/main.go` won't worker and neither `go build worker/main.go`

The main reason for this is that in go you can't pass a function of a struct to anything essentially.

this line https://github.com/temporalio/temporal-ecommerce/blob/main/worker/main.go#L23 will never compile.

```
ep@macbook-pro temporal-ecommerce % go run worker/main.go
# command-line-arguments
worker/main.go:23:21: undefined: app.CreateStripeCharge
worker/main.go:24:21: undefined: app.SendAbandonedCartEmail
```

This example is really helpful in general as it serves as a reference to how design your application but it would be great to have a working one as well. Thanks again!

**Comment by vkarpov15** [comment]
Thanks for reporting, looks like we missed this when refactoring for #8. Should be fixed by #12 :+1:
