### ISSUE TITLE
[Bug] Checkout Doesn't Work

### ISSUE THREAD

**Issue by DJSanti** [temporalio/temporal-ecommerce#35]
### What are you really trying to do?

I'm trying to check out my cart, which should send an email and finish the workflow.

### Describe the bug

Cart checkout doesn't work. I have run this with two email addresses; it doesn't send, and the cart doesn't clear. Instead, the UI hangs on to this, even as the API says it updates.

The only way I've been able to get the UI to refresh is to go clear my cookies. Even then, I still don't get an email sent, and the transaction isn't going through.

![Screenshot 2022-11-18 at 5 12 44 PM](https://user-images.githubusercontent.com/26655231/202818644-3c2ddc01-29e2-4c35-b04b-d06be87cb314.png)

### Environment/Versions

M1 Mac
Temporal 1.18
Docker Compose

### Additional context

Make sure you only have one Worker at a time, or this will get even more erroneous.

**Comment by vkarpov15** [comment]
I took a closer look and this is indicative of not setting the environment variables we need to make checkout work. The error handling around those environment variables is non-existent, we'll fix that.
